[package]
name = "demo_dll"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.98"
proxy_dll = { version = "0.1.0", path = ".." }
windows = { version = "0.61.3", features = ["Win32_System_SystemServices", "Win32_Foundation"] }
